---
- name: Install all needed packages
  include: install.yml
  tags: ["install"]

- name: Create Users
  include: users.yml
  tags: ["user"]

- name: Create security releated stuff
  include: security.yml
  tags: ["security"]