---
- name: Install all needed packages
  include: install.yml
  tags: ["install"]

- name: Create htpasswd files
  include: htpasswd.yml
  tags: ["install"]

- name: Create Users
  include: users.yml
  tags: ["install"]