---
- name: Add Groups
  group:
    name: "{{ item }}"
    state: present
  with_items:
  - "{{ user.groups }}"

- name: Add Users
  user:
    name: "{{ user.name }}"
    group: "{{ user.primary_group }}"
    groups: "{{ user.groups }}"
    home: "{{ user.home }}"
    state: present

- name: Add Authorized Keys
  authorized_key:
    user: "{{ user.name }}"
    key: "{{ user.key }}"