---
environments:
  prod:
    name: prod
    stack: common_prod
    traefik_network: common_prod_traefik
    group: common-prod
    versions:
      record_jar_converter_rest_api: "1.5.2"
      record_jar_converter_site: "1.5.2"
      record_jar_converter: "1.5.2"
      visualizer: "stable"
      traefik: "v1.7"
      json: "1.0.3"
      xml: "1.0.0"
    replicas:
      record_jar_converter_rest_api: 1
      record_jar_converter_site: 1
      visualizer: 1
      traefik: 1
    frontend_rules:
      record_jar_converter_rest_api: "Host:record-jar-converter.pro-crafting.com;PathPrefix:/record-jar-converter-rest-api"
      record_jar_converter_site: "Host:record-jar-converter.pro-crafting.com"
      record_jar_converter: "Host:record-jar-converter.pro-crafting.com;PathPrefix:/v1/record"
      visualizer: "Host:visualizer.pro-crafting.com"
      traefik: "Host:monitor.pro-crafting.com"
      json: "Host:json.pro-crafting.com"
      xml: "Host:xml.pro-crafting.com,xmlpretty.com,xmlpretty.de"
  dev:
    name: dev
    stack: common_dev
    traefik_network: common_dev_traefik
    group: common-dev
    versions:
      record_jar_converter_rest_api: "latest"
      record_jar_converter_site: "latest"
      record_jar_converter: "latest"
      mongodb: "4.1"
      jwt: "latest"
      json: "latest"
      xml: "latest"
      jenkins: "1.1.1"
      visualizer: "stable"
      traefik: "v1.7"
    replicas:
      record_jar_converter_rest_api: 1
      record_jar_converter_site: 1
      jenkins: 1
      visualizer: 1
      traefik: 1
    frontend_rules:
      record_jar_converter_rest_api: "Host:record-jar-converter.dev.pro-crafting.com;PathPrefixStrip:/record-jar-converter-rest-api"
      record_jar_converter_site: "Host:record-jar-converter.dev.pro-crafting.com"
      record_jar_converter: "Host:record-jar-converter.dev.pro-crafting.com;PathPrefix:/v1/record"
      jwt: "Host:jwt.dev.pro-crafting.com;PathPrefix:/jwt-api/v1,/openapi,/swagger-ui"
      json: "Host:json.dev.pro-crafting.com"
      xml: "Host:xml.dev.pro-crafting.com"
      jenkins: "Host:jenkins.build.pro-crafting.com"
      visualizer: "Host:visualizer.dev.pro-crafting.com"
      traefik: "Host:monitor.dev.pro-crafting.com"