---
versions:
  traefik: "v1.7.9"
  record_jar_converter: "1.3.3"
  visualizer: "stable"

service_definitions:
  traefik:
    name: traefik
    template_name: "traefik/traefik"
    tag: "{{ versions.traefik }}"
    environments:
      - "{{ environments.prod }}"
    files:
      - name: "traefik/acme.json"
        overwrite: false
        mode: "0600"
    networks:
      - name: "common_build_traefik"
        driver: "overlay"
      - name: "common_dev_traefik"
        driver: "overlay"
      - name: "common_prod_traefik"
        driver: "overlay"
  visualizer:
    name: visualizer
    image: dockersamples/visualizer
    internal_port: 8080
    environments:
      - "{{ environments.prod }}"
    constraints:
      - "node.role == manager"
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    features:
      - "secure"
  record_jar_converter_rest_api:
    name: record_jar_converter_rest_api
    image: postremus/record-jar-converter-rest-api
    internal_port: 8043
    environments:
      - "{{ environments.prod }}"
      - "{{ environments.dev }}"
    constraints:
      - "node.role == worker"
    features:
      - "secure"
    labels:
      - "traefik.frontend.headers.customResponseHeaders=Access-Control-Allow-Origin:*"
  record_jar_converter_site:
    name: record_jar_converter_site
    image: postremus/record-jar-converter-site
    internal_port: 8043
    environments:
      - "{{ environments.prod }}"
      - "{{ environments.dev }}"
    constraints:
      - "node.role == worker"
    features:
      - "secure"
  record_jar_converter:
    name: record_jar_converter
    image: postremus/record-jar-converter-web
    internal_port: 8080
    environments:
      - "{{ environments.prod }}"
      - "{{ environments.dev }}"
    constraints:
      - "node.role == worker"
    features:
      - "secure"
  jenkins:
    name: jenkins
    image: postremus/jenkins
    internal_port: 8080
    environments:
      - "{{ environments.build }}"
    constraints:
      - "node.role == worker"
    features:
      - "secure"
    volumes:
      - type: volume
        source: jenkins-data
        target: /var/jenkins_home
      - type: bind
        source: /root/id_rsa_docker
        target: /var/jenkins_home/.ssh/id_rsa
    named_volumes:
      - name: jenkins-data
        driver: rexray/dobs