---
versions:
  traefik: "v1.7.3"
  record_jar_converter: "1.3.3"
  visualizer: "stable"

service_definitions:
  traefik:
    name: traefik
    template_name: "traefik/traefik"
    tag: "{{ versions.traefik }}"
    files:
      - name: "traefik/acme.json"
        overwrite: false
        mode: "0600"
  visualizer:
    name: visualizer
    image: dockersamples/visualizer
    tag: "{{ versions.visualizer }}"
    constraints:
      - "node.role == manager"
    replicas: 1
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    features:
      - "secure"
    labels:
      - "traefik.port=8080"
      - "traefik.backend=visualizer-{{env}}"
      - "traefik.frontend.rule={{ frontend_rules.visualizer }}"
      - "traefik.docker.network={{ traefik_network }}"
  record_jar_converter_rest_api:
    name: record-jar-converter-rest-api
    image: postremus/record-jar-converter-rest-api
    tag: "{{ versions.record_jar_converter }}"
    constraints:
      - "node.role == worker"
      - "node.labels.environment == {{ env }}"
    features:
      - "secure"
    replicas: "{{ replicas.record_jar_converter }}"
    labels:
      - "traefik.port=8043"
      - "traefik.backend=record-jar-converter-rest-api-{{env}}"
      - "traefik.frontend.rule={{ frontend_rules.record_jar_converter_rest_api }}"
      - "traefik.docker.network={{ traefik_network }}"
      - "traefik.frontend.headers.customResponseHeaders=Access-Control-Allow-Origin:*"
  record_jar_converter:
    name: record-jar-converter
    image: postremus/record-jar-converter-web
    tag: "{{ versions.record_jar_converter }}"
    constraints:
      - "node.role == worker"
      - "node.labels.environment == {{ env }}"
    features:
      - "secure"
    replicas: "{{ replicas.record_jar_converter }}"
    labels:
      - "traefik.port=8080"
      - "traefik.backend=record-jar-converter-{{env}}"
      - "traefik.frontend.rule={{ frontend_rules.record_jar_converter }}"
      - "traefik.docker.network={{ traefik_network }}"