---
versions:
  traefik: "v1.7.9"
  record_jar_converter: "1.3.3"
  visualizer: "stable"

service_definitions:
  traefik:
    name: traefik
    template_name: "traefik/traefik"
    tag: "{{ versions.traefik }}"
    files:
      - name: "traefik/acme.json"
        overwrite: false
        mode: "0600"
    networks:
      - name: "common_build_traefik"
        driver: "overlay"
      - name: "common_dev_traefik"
        driver: "overlay"
      - name: "common_prod_traefik"
        driver: "overlay"
  visualizer:
    name: visualizer
    image: dockersamples/visualizer
    tag: "{{ versions.visualizer }}"
    constraints:
      - "node.role == manager"
    replicas: 1
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    features:
      - "secure"
    labels:
      - "traefik.port=8080"
      - "traefik.backend=visualizer-{{env}}"
      - "traefik.frontend.rule={{ frontend_rules.visualizer }}"
      - "traefik.docker.network={{ traefik_network }}"
  record_jar_converter_rest_api:
    name: record-jar-converter-rest-api
    image: postremus/record-jar-converter-rest-api
    tag: "{{ versions.record_jar_converter }}"
    constraints:
      - "node.role == worker"
      - "node.labels.environment == {{ env }}"
    features:
      - "secure"
    replicas: "{{ replicas.record_jar_converter }}"
    labels:
      - "traefik.port=8043"
      - "traefik.backend=record-jar-converter-rest-api-{{env}}"
      - "traefik.frontend.rule={{ frontend_rules.record_jar_converter_rest_api }}"
      - "traefik.docker.network={{ traefik_network }}"
      - "traefik.frontend.headers.customResponseHeaders=Access-Control-Allow-Origin:*"
  record_jar_converter_site:
    name: record-jar-converter-site
    image: postremus/record-jar-converter-site
    tag: "{{ versions.record_jar_converter }}"
    constraints:
      - "node.role == worker"
      - "node.labels.environment == {{ env }}"
    features:
      - "secure"
    replicas: "{{ replicas.record_jar_converter }}"
    labels:
      - "traefik.port=8043"
      - "traefik.backend=record-jar-converter-site-{{env}}"
      - "traefik.frontend.rule={{ frontend_rules.record_jar_converter_site }}"
      - "traefik.docker.network={{ traefik_network }}"
      - "traefik.frontend.headers.customResponseHeaders=Access-Control-Allow-Origin:*"
  record_jar_converter:
    name: record-jar-converter
    image: postremus/record-jar-converter-web
    tag: "{{ versions.record_jar_converter }}"
    constraints:
      - "node.role == worker"
      - "node.labels.environment == {{ env }}"
    features:
      - "secure"
    replicas: "{{ replicas.record_jar_converter }}"
    labels:
      - "traefik.port=8080"
      - "traefik.backend=record-jar-converter-{{env}}"
      - "traefik.frontend.rule={{ frontend_rules.record_jar_converter }}"
      - "traefik.docker.network={{ traefik_network }}"
  jenkins:
    name: jenkins
    image: postremus/jenkins
    tag: "{{ versions.jenkins }}"
    constraints:
      - "node.role == worker"
      - "node.labels.environment == {{ env }}"
    features:
      - "secure"
    replicas: "1"
    labels:
      - "traefik.port=8080"
      - "traefik.backend=jenkins-{{env}}"
      - "traefik.frontend.rule={{ frontend_rules.jenkins }}"
      - "traefik.docker.network={{ traefik_network }}"
    volumes:
      - type: volume
        source: jenkins-data
        target: /var/jenkins_home
      - type: bind
        source: /root/id_rsa_docker
        target: /var/jenkins_home/.ssh/id_rsa
    named_volumes:
      - name: jenkins-data
        driver: rexray/dobs