---

service_definitions:
  traefik:
    name: traefik
    template_name: "traefik/traefik"
    tag: "{{ versions.traefik }}"
    files:
      - name: "traefik/acme.json"
        overwrite: false
        mode: "0600"
  record_jar_converter_rest_api:
    name: record-jar-converter-rest-api
    image: postremus/record-jar-converter-rest-api
    tag: "{{ versions.record_jar_converter }}"
    features:
     - "secure"
    labels:
     - "traefik.port=8043"
     - "traefik.backend=record-jar-converter-rest-api"
     - "traefik.frontend.rule={{ frontend_rules.record_jar_converter_rest_api }}"
     - "traefik.docker.network={{ stack.name }}_traefik"
     - "traefik.frontend.headers.customResponseHeaders=Access-Control-Allow-Origin:*"
  record_jar_converter:
    name: record-jar-converter
    image: postremus/record-jar-converter-web
    tag: "{{ versions.record_jar_converter }}"
    constraints:
      - "node.role == worker"
      - "node.labels.environment={{ environment }}"
    features:
     - "secure"
    labels:
     - "traefik.port=8080"
     - "traefik.backend=record-jar-converter"
     - "traefik.frontend.rule={{ frontend_rules.record_jar_converter }}"
     - "traefik.docker.network={{ stack.name }}_traefik"
  visualizer:
    name: visualizer
    image: dockersamples/visualizer
    tag: "{{ versions.visualizer }}"
    constraints:
      - "node.role == manager"
    replicas: 1
    volumes:
     - "/var/run/docker.sock:/var/run/docker.sock"
    features:
     - "secure"
    labels:
     - "traefik.port=8080"
     - "traefik.backend=visualizer"
     - "traefik.frontend.rule={{ frontend_rules.visualizer }}"
     - "traefik.docker.network={{ stack.name }}_traefik"