language: generic
sudo: required

before_install:
  - chmod +x .travis/*.sh
  - "./.travis/before-install.sh"
install: true
jobs:
  include:
    - stage: deployment
      script:
        - "./.travis/cron-dev.sh"