---
stack:
  name: "common_prod"

traefik_network: "common_prod_traefik"

env: "prod"
docker:
  node_labels:
  - name: "environment"
    value: "{{ env }}"

deployments:
  - rjc
  - visualizer
  - traefik