---
- name: "{{service.name}} - Create directory for service definitions"
  file:
    path: "{{ docker_service_dir }}/{{env.stack}}/{{ service.name }}"
    state: directory

- name: "{{service.name}} - Copy service definition to remote"
  template:
    src: "files/{{ service.template_name | default('common-traefik-app') }}.j2"
    dest: "{{ docker_service_dir }}/{{env.stack}}/{{ service.name }}/{{ service.name }}.yml"

- name: "{{service.name}} - Copy additional configuration files to remote"
  copy:
    src: "files/{{ file.path }}"
    dest: "{{ docker_service_dir }}/{{env.stack}}/{{ service.name }}/{{ file.path | basename }}"
    force: "{{ file.overwrite | default('false') }}"
    mode: "{{ file.mode | default('0644') }}"
  when: "service.files is defined"
  loop: "{{ service.files }}"
  loop_control:
    loop_var: "file"

- name: "Create needed networks"
  docker_network:
    name: "{{ network.name }}"
    driver: "{{ network.driver }}"
  when: "service.networks is defined"
  loop: "{{ service.networks }}"
  loop_control:
    loop_var: "network"

- name: "{{service.name}} - Update Service"
  docker_stack:
    name: "{{ env.stack }}"
    compose: "{{ docker_service_dir }}/{{env.stack}}/{{ service.name }}/{{ service.name }}.yml"
    resolve_image: always
