---
- name: "{{service.name}} - Create directory for service definitions"
  file:
    path: "{{ docker_service_dir }}/{{env.stack}}/{{ service.name }}"
    state: directory

- name: "{{service.name}} - Copy service definition to remote"
  template:
    src: "files/{{ service.template_name | default('common-traefik-app') }}.j2"
    dest: "{{ docker_service_dir }}/{{env.stack}}/{{ service.name }}/{{ service.name }}.yml"

- name: Create config from file on the ansible control machine
  docker_config:
    name: "{{config.name}}"
    data: "{{ lookup('file', 'files/{{ config.path }}') | b64encode }}"
    data_is_b64: true
    state: present
  when: "service.configs is defined"
  loop: "{{ service.configs }}"
  loop_control:
    loop_var: "config"

- name: "Create needed networks"
  docker_network:
    name: "{{ network.name }}"
    driver: "{{ network.driver }}"
  when: "service.networks is defined"
  loop: "{{ service.networks }}"
  loop_control:
    loop_var: "network"

- name: "{{service.name}} - Update Service"
  docker_stack:
    name: "{{ env.stack }}"
    compose: "{{ docker_service_dir }}/{{env.stack}}/{{ service.name }}/{{ service.name }}.yml"
    resolve_image: always