---
- name: Uninstall existing obsolete docker packages
  include: uninstall.yml
  tags: ["uninstall"]

- name: install docker-ce
  include: install.yml
  tags: ["install"]

- name: Setup Swarm
  include: swarm.yml
  tags: ["swarm"]

- name: Setup Node
  include: node.yml
  tags: ["node"]

- name: Create meta
  include: meta.yml
  tags: ["secret"]