---
- name: Remove all node labels
  docker_node:
    hostname: "{{ ansible_hostname }}"
    labels_state: replace
  delegate_to: "{{ groups['docker-swarm-manager'][0] }}"

- name: Create docker node labels
  docker_node:
    hostname: "{{ ansible_hostname }}"
    labels: "{{ docker_node_labels }}"
  when: "docker_node_labels is defined"
  delegate_to: "{{ groups['docker-swarm-manager'][0] }}"