---

- name: Install docker plugin
  shell: "docker plugin install --disable --grant-all-permissions {{ item.name }} "
  when: "docker_plugins is defined"
  loop: "{{ docker_plugins }}"
  ignore_errors: yes

- name: Disable plugins
  shell: "docker plugin disable {{ item.name }}"
  when: "docker_plugins is defined"
  loop: "{{ docker_plugins }}"
  ignore_errors: yes

- name: Set plugin settings
  shell: "docker plugin set {{ item.name }} {{ item.environment }}"
  when: "docker_plugins is defined"
  loop: "{{ docker_plugins }}"

- name: Enable plugins
  shell: "docker plugin enable {{ item.name }}"
  when: "docker_plugins is defined"
  loop: "{{ docker_plugins }}"